// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";
import { resolveMigrationUrl } from "./src/lib/dbUrl";

// Migrations need a direct (non-pooled) connection. resolveMigrationUrl accepts
// a manually-set DATABASE_URL, the standard Vercel/Neon Postgres vars, or those
// same vars under any custom prefix the host applied.
const migrationUrl = resolveMigrationUrl();

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  datasource: {
    url: migrationUrl,
  },
});
